### PR TITLE
fix: upgrade node-gyp to fix macOS build error

### LINKED ISSUE #643: OSX failure...
**using node@18.18.2 | darwin | x64**

```
npm ERR! code 1
npm ERR! path /Users/runner/work/wshell2/wshell2/clients/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.2 | darwin | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "/usr/local/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.2/node-v18.18.2-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.2/node-v18.18.2-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.2/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.2/SHASUMS256.txt
npm ERR! gyp info spawn /usr/local/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/runner/work/wshell2/wshell2/clients/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/runner/Library/Caches/node-gyp/18.18.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/runner/Library/Caches/node-gyp/18.18.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/runner/Library/Caches/node-gyp/18.18.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/runner/work/wshell2/wshell2/clients/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E[40](https://github.com/Zibri/wshell2/actions/runs/7077717769/job/19262368819#step:2:41)2
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:[51](https://github.com/Zibri/wshell2/actions/runs/7077717769/job/19262368819#step:2:52)7:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node@18/18.18.2/bin/node" "/usr/local/Cellar/node@18/18.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/runner/work/wshell2/wshell2/clients/node_modules/node-pty
npm ERR! gyp ERR! node -v v18.18.2
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
```

### LINKED ISSUE #646: Upgrade node-gyp to support Python 3.12
## Environment details

- OS: windows
- OS version: windows 11
- node-pty version: 1.0

## Issue description
See https://github.com/nodejs/node-gyp/issues/2869 
https://github.com/microsoft/node-pty/issues/643

### PR DESCRIPTION
**Pull request by kkocdko**
Fix #643

Fix #646

### CODE REVIEW

**Comment by kkocdko** [comment]
@deepak1556 Hi, could you please take the time to merge this, it would be very useful for macOS (and other environment with Python 3.12) users, thank you very much!

**Comment by kkocdko** [comment]
Not sure why [APIScan failed](https://dev.azure.com/vscode/87865b3e-0548-40e8-b5d9-d602b3c3bc01/_apis/build/builds/117334/logs/68) .

**Review by deepak1556 — APPROVED** [review]
LGTM, thanks!

**Comment by deepak1556** [comment]
@sbatten @rzhao271 there is an auth issue with APIScan run, can this be ignored for now ?

```
ERROR: System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Tools.ApiScan.ApiScanLib.DataStore.SqlAuthProvider' threw an exception. ---> System.ArgumentException: Connection string $(apiscan-connectionstring) is not in a proper format. Expected format is Key1=Value1;Key2=Value2;
```

**Review by bpasero — APPROVED** [review]

**Comment by rzhao271** [comment]
The APIScan issue is unrelated. Merging the PR.

**Comment by deepak1556** [comment]
@rzhao271 is the APIScan auth issue tracked somewhere ?

**Pull request merged**
