### PR TITLE
fixed symbolic link dereference when launching shell

### PR DESCRIPTION
**Pull request by vvavrychuk**
Without this if we pty.spaw with cwd beeing a symbolic link,
then actually shell will be opened with cwd dereferenced.

### CODE REVIEW

**Comment by Tyriar** [comment]
@vvavrychuk by dereferenced do you mean it follows the cwd? Is this not expected/ideal?

**Comment by vvavrychuk** [comment]
@Tyriar I mean suppose we have folder `A` being symbolic link to `B`. If we pass `A` as cwd to node-pty then after launch actual cwd will be `B`.

I am not sure what is ideal, but:
- I needed this to implement change similar to https://github.com/Microsoft/vscode/issues/18837 on vscode terminal
- Maybe if user wants dereference than he can do realpath in advance.
- I tried to start xterm and see that it does not perform dereference

**Comment by Tyriar** [comment]
@vvavrychuk oh I see. Do you have a link to documentation describing the `$PWD` environment variable's behavior? Need to make sure this works on macOS and linux. We may also be able to create a unit test for this one.

**Comment by vvavrychuk** [comment]
I dropped using patch ended up using `mount --bind` instead of symbolic links. Problem is that even if we change behavior in VS code, similar thing exists in other software.

**Comment by Tyriar** [comment]
@vvavrychuk I'm still open to merging this in, I just want to make sure I understand the behavior of `$PWD`

**Comment by Tyriar** [comment]
@vvavrychuk I've learned more about this myself over time and got pinged in https://github.com/microsoft/vscode/issues/59291 about it, this is totally the expected behavior as it's how `cd` works. Thanks for the contribution and sorry about not merging 2 years ago 🙂

**Pull request merged**
