### PR TITLE
ConPTY Support

### LINKED ISSUE #7: Ctrl-C doesn't terminate process or clear the line
From https://github.com/Microsoft/vscode/issues/15249

> - VSCode Version: 1.7.1
> - OS Version: Windows 8.1
> 
> Steps to Reproduce:
> 
> 1. "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
> 2. Ctrl-C doesn't work for terminating a process (such as cordova run).

### LINKED ISSUE #216: Support ConPTY on Windows 10
https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

Related: https://github.com/Microsoft/vscode/issues/45693

### PR DESCRIPTION
**Pull request by Tyriar**
This introduces ConPTY support to node-pty which will be used when the Windows version is >=17692, there will also be a setting to allow consumers to say which to use.

Fixes #7
Fixes #216

### TODO

- [x] Clean up
- [x] Make sure unix support still works
- [x] Resolve TODOs
- [x] Document `NODE_PTY_DEBUG` environment variable in https://github.com/Microsoft/node-pty/wiki/Debugging
- [x] `exit` doesn't kill terminal in vscode

### CODE REVIEW

**Comment by Tyriar** [comment]
@Astrantia it's mostly done but it's blocked on VS Code adopting Electron 3 https://github.com/Microsoft/vscode/issues/52629

**Comment by ExE-Boss** [comment]
https://github.com/Microsoft/vscode/pull/56149 has been merged and https://github.com/Microsoft/vscode/issues/52629 has been closed as&nbsp;a&nbsp;result.

**Comment by Eugeny** [comment]
I've merged this PR into Terminus - the initial results are great! Are there plans to add mouse support as well (MOUSE_EVENT_RECORD etc)?

**Comment by Tyriar** [comment]
@Eugeny you can report conpty-specific issues to https://github.com/Microsoft/console

**Comment by Tyriar** [comment]
@Eugeny also be warned the PR isn't complete just yet, the terminal's aren't cleaned up after they exit and no event is fired for example.

**Comment by Astrantia** [comment]
@Tyriar Is this ready to be used in Code Insiders?

**Comment by Tyriar** [comment]
@Astrantia very soon 😃

**Comment by Tyriar** [comment]
Let's do this 🚀 💥 😱 🏗 🏎 😎

**Pull request merged**
