### PR TITLE
Ship conpty.dll/OpenConsole.exe with opt-in experimental option useConptyDll

### PR DESCRIPTION
**Pull request by Tyriar**
This also includes header files for node v20.14.0 so that go to def/etc. work in the C++ vscode extension.

Part of microsoft/vscode#224488

### CODE REVIEW

**Review by rzhao271 — APPROVED** [review]

**Comment by deepak1556** [comment]
@Tyriar why not point to the node-gyp which your installation of node uses instead of bundling it in the repo ?

**Comment by Tyriar** [comment]
@deepak1556 how would you do that in a portable way as node could be installed anywhere?

**Comment by deepak1556** [comment]
Prefer [compile_commands](https://clang.llvm.org/docs/JSONCompilationDatabase.html) which makes intellisense work on the header and library paths specified to the compiler at build time. The c++ extensions seems to support it https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference#_configuration-properties. Most build systems out there should support generating this file. For node-gyp refer to https://github.com/nodejs/node-gyp/issues/1526

The dependency added in this PR will be hard to maintain and quickly go out of sync, it would be best if we avoid syncing it to the repo.

**Comment by Tyriar** [comment]
I only realized it was a million lines after merging 😅

**Pull request merged**
