### PR TITLE
Rethrow Release require exception if Debug require fails

### LINKED ISSUE #326: Rethrow error when both release and debug native require fails
Lots of users see the cannot find module debug error, we should rethrow the error so users can help themselves.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #326

### CODE REVIEW

**Comment by bet4it** [comment]
We may also need `console.error('outerError', outerError)` somewhere?

**Comment by Tyriar** [comment]
@bet4it well it gets thrown so you would be able to catch and log it if you want to?

**Comment by bet4it** [comment]
But thus we can't get some useful messages of `outerError` like `The module was compiled against a different Node.js version`

**Comment by Tyriar** [comment]
@bet4it it's thrown so you can catch it and log:

```ts
let pty;
try {
  pty = require('node-pty');
} catch (outerError) {
  console.error('outerError', outerError);
}
```

**Pull request merged**
