### PR TITLE
block signals during forking

### PR DESCRIPTION
**Pull request by jerch**
~~WIP - do not merge (yet)~~

This is a first version to deal with the signal problem during spawning the pty and forking. ~~Not tested yet due to missing test cases.~~ (some test cases added).

### CODE REVIEW

**Comment by fpronto** [comment]
good for me

**Comment by jerch** [comment]
The tests cover:
- killing with SIGHUP, which works now but didnt before for some unknown reason
- some custom signal handler for SIGUSR1 will stay in place for parent and child
- previously attached SIGINT handlers work as expected in parent and child

**Comment by olivierchatry** [comment]
Very nice ! Would be very cool to have that, as it is a bit of a problem when you have clean up to do in your "main" process if user interrupt it.

**Comment by olivierchatry** [comment]
Just checking if this will merge soon. Sorry for being pushy, but it is kind of important for my project.

**Comment by Jesse-Schokker** [comment]
This is quite a serious bug. Can someone merge it in already please?

**Comment by gae123** [comment]
We really need this fix, what is blocking its integration?

**Comment by jerch** [comment]
@Tyriar Well the changes do the following:
- temporarily block signals during forking (to avoid a race condition)
- set signal handlers in child to default handler (to avoid triggering parent handlers in the child between fork --> exec)
- re-enable signals:
  - parent: restore prev handlers
  - child: execs into foreign binary with default signal handlers, thus the binary behaves as expected from a clean start
- remove resetting of SIGINT handler, which causes most issues listed

I dont expect negative side effects on vscode here, but cannot tell that for sure. There is a small chance, that some code might rely on the faulty handling of the old code.

I think removing the race conditions makes things more stable (its just an edge case, thus hardly triggered/seen by anyone, but I think that the old code could segfault the process if triggered). And not resetting the SIGINT handler in the parent should fix the issues most ppl have with the old code.

So yes I think this is good to go. You still might want to check in vscode, if spawning/closing pty processes triggers weird behavior afterwards like dysfunctional `process.on('some_signal')` handlers. I dont think so.

**Comment by Tyriar** [comment]
Merging and will see if there are problems in the first vscode 1.45 insiders build

**Comment by NuSkooler** [comment]
Any update on getting this into a release?

**Comment by Tyriar** [comment]
@NuSkooler you can use the `beta` tag to get the latest version, no date for 0.10 yet

**Pull request merged**
